# Generated by Django 2.1.3 on 2019-07-07 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttentionPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_content', models.TextField()),
                ('c_user', models.IntegerField()),
                ('c_b_commentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='DynamicStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_time', models.DateTimeField(auto_now_add=True)),
                ('d_content', models.TextField()),
                ('d_type', models.CharField(max_length=10)),
                ('d_num', models.IntegerField()),
                ('d_b_time', models.DateTimeField(auto_now_add=True)),
                ('d_z_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(upload_to='image')),
                ('image_time', models.DateTimeField(auto_now_add=True)),
                ('image_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_sex', models.CharField(max_length=20)),
                ('user_sign', models.TextField()),
                ('user_birth', models.DateField()),
                ('user_city', models.CharField(max_length=20)),
                ('user_one_level', models.IntegerField()),
                ('user_member_level', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='photoalbum',
            name='user_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='dynamicstatus',
            name='d_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='c_b_dynamic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.DynamicStatus'),
        ),
        migrations.AddField(
            model_name='comment',
            name='c_b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='attentionperson',
            name='a_b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
    ]
