# Generated by Django 2.1.4 on 2019-07-08 21:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_b_user', models.IntegerField()),
                ('g_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Move_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_b_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('d_user', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thumps_up',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='dynamicstatus',
            old_name='d_user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='dynamicstatus',
            name='d_b_time',
        ),
        migrations.RemoveField(
            model_name='dynamicstatus',
            name='d_num',
        ),
        migrations.RemoveField(
            model_name='dynamicstatus',
            name='d_type',
        ),
        migrations.RemoveField(
            model_name='dynamicstatus',
            name='d_z_user',
        ),
        migrations.AddField(
            model_name='dynamicstatus',
            name='d_picture',
            field=models.FileField(null=True, upload_to='picture', validators=[django.core.validators.FileExtensionValidator('jpg', 'png', 'txt')]),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_numbers',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='thumps_up',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='body.DynamicStatus'),
        ),
        migrations.AddField(
            model_name='thumps_up',
            name='u',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='move_text',
            name='d_z_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
        migrations.AddField(
            model_name='guestlog',
            name='g_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo'),
        ),
    ]
