# Generated by Django 2.1.3 on 2019-07-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20190708_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_member_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_one_level',
            field=models.IntegerField(default=0),
        ),
    ]
