# Generated by Django 2.1.4 on 2019-07-09 02:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20190708_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicstatus',
            name='d_picture',
            field=models.FileField(max_length=1000, null=True, upload_to='picture', validators=[django.core.validators.FileExtensionValidator('jpg', 'png', 'txt')]),
        ),
    ]
