# Generated by Django 2.1.4 on 2019-07-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20190716_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_birth',
            field=models.DateField(auto_now_add=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_sex',
            field=models.CharField(default='请修改', max_length=20, verbose_name='性别'),
        ),
    ]
