# Generated by Django 2.1.4 on 2019-07-09 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_auto_20190709_1016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumps_up',
            name='date',
        ),
    ]
