# Generated by Django 2.1.4 on 2019-07-18 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_auto_20190718_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_b_dynamic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='body.DynamicStatus'),
        ),
    ]
