# Generated by Django 2.1.4 on 2019-07-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_remove_thumps_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicstatus',
            name='d_num',
            field=models.IntegerField(default=0),
        ),
    ]
