# Generated by Django 2.1.3 on 2019-07-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_auto_20190718_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_PORT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_jude',
            field=models.IntegerField(default=0),
        ),
    ]
