# Generated by Django 2.1.4 on 2019-07-10 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0005_dynamicstatus_d_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='love',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo')),
            ],
        ),
        migrations.AddField(
            model_name='dynamicstatus',
            name='d_like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='love',
            name='u_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.DynamicStatus'),
        ),
    ]
