# Generated by Django 2.1.4 on 2019-07-10 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0006_auto_20190710_0914'),
    ]

    operations = [
        migrations.RenameField(
            model_name='love',
            old_name='u_article',
            new_name='U_Article',
        ),
    ]
