# Generated by Django 2.1.4 on 2019-07-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0007_auto_20190710_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicstatus',
            name='new_content',
            field=models.TextField(null=True),
        ),
    ]
