# Generated by Django 2.1.4 on 2019-07-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0003_auto_20190709_2024'),
        ('body', '0008_dynamicstatus_new_content'),
    ]

    operations = [
    ]
