# Generated by Django 2.1.4 on 2019-07-11 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0009_merge_20190711_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='levelsystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signnumber', models.IntegerField(db_column='sign_num', default=0)),
                ('memberopendata', models.DateField(db_column='member_open_data', null=True)),
                ('duedata', models.DateField(db_column='member_due_data', null=True)),
                ('sign', models.IntegerField(default=0)),
                ('userid', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo')),
            ],
            options={
                'db_table': 'level_system',
            },
        ),
    ]
