# Generated by Django 2.1.4 on 2019-07-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0009_merge_20190710_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicstatus',
            name='new_content',
        ),
        migrations.AddField(
            model_name='move_text',
            name='new_content',
            field=models.TextField(null=True),
        ),
    ]
