# Generated by Django 2.1.4 on 2019-07-12 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0010_levelsystem'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelsystem',
            name='userimg',
            field=models.TextField(default='exit', verbose_name='用户头像编码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='levelsystem',
            name='duedata',
            field=models.DateField(db_column='member_due_data', null=True, verbose_name='会员到期时间'),
        ),
        migrations.AlterField(
            model_name='levelsystem',
            name='memberopendata',
            field=models.DateField(db_column='member_open_data', null=True, verbose_name='会员充值日期'),
        ),
        migrations.AlterField(
            model_name='levelsystem',
            name='sign',
            field=models.IntegerField(default=0, verbose_name='当天是否签到'),
        ),
        migrations.AlterField(
            model_name='levelsystem',
            name='signnumber',
            field=models.IntegerField(db_column='sign_num', default=0, verbose_name='登陆天数'),
        ),
        migrations.AlterField(
            model_name='levelsystem',
            name='userid',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo', verbose_name='用户id'),
        ),
    ]
