# Generated by Django 2.1.4 on 2019-07-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0010_auto_20190710_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='move_text',
            name='worn_content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='move_text',
            name='worn_picture',
            field=models.TextField(null=True),
        ),
    ]
