# Generated by Django 2.1.4 on 2019-07-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0011_auto_20190712_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelsystem',
            name='sign',
            field=models.BooleanField(default=False, verbose_name='当天是否签到'),
        ),
        migrations.AlterField(
            model_name='levelsystem',
            name='signnumber',
            field=models.IntegerField(db_column='sign_num', verbose_name='登陆天数'),
        ),
    ]
