# Generated by Django 2.1.4 on 2019-07-10 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0011_auto_20190710_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move_text',
            name='new_content',
        ),
        migrations.RemoveField(
            model_name='move_text',
            name='worn_content',
        ),
        migrations.RemoveField(
            model_name='move_text',
            name='worn_picture',
        ),
        migrations.AddField(
            model_name='dynamicstatus',
            name='new_content',
            field=models.TextField(null=True),
        ),
    ]
