# Generated by Django 2.1.4 on 2019-07-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0013_dynamicstatus_d_move'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_b_commentID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='body.Comment'),
        ),
    ]
