# Generated by Django 2.1.4 on 2019-07-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0012_auto_20190712_0935'),
        ('body', '0014_auto_20190712_1010'),
    ]

    operations = [
    ]
