# Generated by Django 2.1.4 on 2019-07-13 19:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0015_merge_20190713_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='c_b_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo', verbose_name='被评用户'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='c_user',
            field=models.IntegerField(verbose_name='评论用户'),
        ),
        migrations.AlterField(
            model_name='dynamicstatus',
            name='d_content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='dynamicstatus',
            name='d_like',
            field=models.IntegerField(default=0, verbose_name='喜欢数'),
        ),
        migrations.AlterField(
            model_name='dynamicstatus',
            name='d_num',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='dynamicstatus',
            name='d_picture',
            field=models.FileField(max_length=1000, null=True, upload_to='picture', validators=[django.core.validators.FileExtensionValidator('jpg', 'png', 'txt')], verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='dynamicstatus',
            name='d_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='dynamicstatus',
            name='new_content',
            field=models.TextField(null=True, verbose_name='转发'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='image_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='image_type',
            field=models.CharField(max_length=10, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='photoalbum',
            name='user_image',
            field=models.ImageField(upload_to='image', verbose_name='图片地址'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_birth',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_city',
            field=models.CharField(max_length=20, verbose_name='所在地'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_member_level',
            field=models.IntegerField(default=0, verbose_name='会员等级'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_numbers',
            field=models.BigIntegerField(null=True, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_one_level',
            field=models.IntegerField(default=0, verbose_name='用户等级'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_password',
            field=models.CharField(max_length=20, null=True, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_sex',
            field=models.CharField(max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user_sign',
            field=models.TextField(verbose_name='个性签名'),
        ),
    ]
