# Generated by Django 2.1.4 on 2019-07-20 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image', models.ImageField(blank=True, upload_to='picture', verbose_name='相册地址')),
                ('image_type', models.TextField(verbose_name='相册类型')),
                ('isDelete', models.IntegerField(default=0)),
                ('user_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='body.UserInfo')),
            ],
            options={
                'verbose_name_plural': '相册',
            },
        ),
        migrations.CreateModel(
            name='PhotoGraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_image_url', models.ImageField(blank=True, upload_to='picture', verbose_name='图片地址')),
                ('isDelete', models.IntegerField(default=0)),
                ('I_A', models.ManyToManyField(to='albums.PhotoAlbum', verbose_name='所属相册')),
            ],
            options={
                'verbose_name_plural': '图片',
            },
        ),
    ]
